version: 1.0
runtime: python3
runtime_version: 3.12
build:
  requirements_file: requirements.txt
  cache_build_dependencies:
    # Configures caching (for faster deployments!)
    enabled: false
    watched_files:
    - requirements.txt
    - tool_config.yaml
    - tool.py
run:
  tool_file: tool.py
  init_tool_file: tool.py
  init_tool_function: init_tool
